package com.deleidos.dp.h2;

import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;
import org.h2.tools.DeleteDbFiles;
import org.h2.tools.Server;

import com.deleidos.dp.beans.BinaryDetail;
import com.deleidos.dp.beans.DataSample;
import com.deleidos.dp.beans.DataSampleMetaData;
import com.deleidos.dp.beans.Detail;
import com.deleidos.dp.beans.NumberDetail;
import com.deleidos.dp.beans.Profile;
import com.deleidos.dp.beans.Schema;
import com.deleidos.dp.beans.SchemaMetaData;
import com.deleidos.dp.beans.StringDetail;
import com.deleidos.dp.exceptions.DataAccessException;
import com.deleidos.hd.h2.H2Config;
import com.deleidos.hd.h2.H2Database;
import com.deleidos.hd.h2.H2TestDatabase;

/**
 * Data access object to persist and retrieve schemas, samples, and metrics from
 * the H2 server.
 * 
 * @author leegc
 * @author yoonj1
 *
 */
public class H2DataAccessObject {
	public static final Logger logger = Logger.getLogger(H2DataAccessObject.class);
	private H2Database h2Database;
	private boolean isLive;
	protected static H2DataAccessObject h2Dao = null;
	private H2MetricsDataAccessObject h2Metrics;
	private H2SampleDataAccessObject h2Samples;
	private H2SchemaDataAccessObject h2Schema;
	public static final boolean debug = false;

	private H2DataAccessObject(H2Database h2Database) {
		this.h2Database = h2Database;
	}

	/**
	 * Get or instantiate the static instance of the H2 Data Access Object.
	 * 
	 * @return The static H2DataAccessObject
	 * @throws DataAccessException 
	 * @throws IOException 
	 */
	public static H2DataAccessObject getInstance() throws DataAccessException {
		if (h2Dao == null) {
			try {
				h2Dao = new H2DataAccessObject(new H2Database());
				h2Dao.initConnection();
			} catch (IOException e) {
				logger.error("Could not find configuration file.");
				logger.error(e);
			}
		}
		return h2Dao;
	}

	public static H2DataAccessObject setInstance(H2Database database) throws DataAccessException {
		h2Dao = new H2DataAccessObject(database);
		return h2Dao;
	}

	/**
	 * Remove all files in the database directory with the database name.
	 */
	public void purge() {
		h2Database.purge();
	}

	/**
	 * Return the generated key from a statement (H2 only allows a maximum of
	 * one to be returned per query). Calling this method will not execute the
	 * statement.
	 * 
	 * @param stmt
	 *            The executed statement
	 * @return The key generated by executing this statement
	 * @throws SQLException
	 *             Thrown if there is an error in the query.
	 */
	public int getGeneratedKey(Statement stmt) throws SQLException {
		ResultSet gKeys = stmt.getGeneratedKeys();
		int fieldId = -1;
		if (gKeys.next()) {
			fieldId = gKeys.getInt(1);
			stmt.close();
		} else {
			stmt.close();
			return -1;
		}
		return fieldId;
	}

	/**
	 * Run a query in H2.
	 * 
	 * @param sql
	 *            The string of the SQL query.
	 * @return The result set from executing this query.
	 * @throws SQLException
	 *             Thrown if there is an error in the query.
	 */
	public ResultSet query(String sql) throws SQLException {
		if (debug) {
			return queryWithOutput(sql);
		} else {
			return getDBConnection().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)
					.executeQuery(sql);
		}
	}

	/**
	 * Run a query in H2 and log the output at the debug level.
	 * 
	 * @param sql
	 *            The string of the SQL query.
	 * @return The result set from executing this query.
	 * @throws SQLException
	 *             Thrown if there is an error in the query.
	 */
	public ResultSet queryWithOutput(String sql) throws SQLException {
		ResultSet rs = query(sql);
		ResultSetMetaData rsmd = rs.getMetaData();
		int c = rsmd.getColumnCount();
		StringBuilder sb = new StringBuilder();
		logger.info(sql);
		for (int i = 1; i <= c; i++) {
			sb.append(rsmd.getColumnName(i) + "\t");
		}
		logger.info(sb);
		while (rs.next()) {
			StringBuilder s = new StringBuilder();
			for (int i = 1; i <= c; i++) {
				s.append(rs.getString(i) + "\t");
			}
			logger.info(s.toString());
		}
		rs.beforeFirst();
		return rs;
	}

	public Connection getDBConnection() {
		// return new connection
		// call driver once
		return h2Database.getDbConnection();
	}

	public H2DataAccessObject initConnection () throws DataAccessException {
		try {
			h2Database.connect();
			h2Metrics = new H2MetricsDataAccessObject(this);
			h2Samples = new H2SampleDataAccessObject(this);
			h2Schema = new H2SchemaDataAccessObject(this);
		} catch(Exception e) {
			throw new DataAccessException("Could not connect to H2Database.", e);
		}
		return this;
	}

	/**
	 * Close the connection.
	 */
	public void closeConnection() throws SQLException {
		h2Database.closeConnection();
	}

	/**
	 * Add a schema to H2.
	 * 
	 * @param schemaBean
	 *            the schema object as a bean
	 * @return The guid of the schema
	 * @throws DataAccessException 
	 */
	public String addSchema(Schema schemaBean) throws DataAccessException {
		if (schemaBean.getsName() == null) {
			schemaBean.setsName(schemaBean.getsGuid());
		}
		if (schemaBean.getsDescription() == null) {
			schemaBean.setsDescription("This is a schema generated by the Schema Wizard.");
		}
		if (schemaBean.getsVersion() == null) {
			schemaBean.setsVersion("1.0");
		}
//		if (schemaBean.getsLastUpdate() == null) {
		// Always update timestamp
		schemaBean.setsLastUpdate(Timestamp.from(Instant.now()));
//		}
		h2Schema.addSchema(schemaBean);
		return schemaBean.getsGuid();
	}

	/**
	 * Update a schema in H2. TODO
	 * 
	 * @param schemaBean
	 *            the schema object as a bean
	 * @return The guid of the schema
	 */
	//	public String updateSchema(Schema schemaBean) {
	//		h2Schema.updateSchema(schemaBean);
	//		
	//		for (Profile : schemaBean.getsProfile())
	//		
	//		return schemaBean.getsGuid();
	//	}

	/**
	 * Get a list of the schema meta data in H2
	 * 
	 * @return a list of SchemaMetaData beans
	 * @throws DataAccessException 
	 */
	public List<SchemaMetaData> getAllSchemaMetaData() throws DataAccessException {
		return h2Schema.getAllSchemaMetaData();
	}

	/**
	 * Get a list of the sample meta data in H2
	 * 
	 * @return a list of SampleMetaDataBeans
	 * @throws DataAccessException 
	 */
	public List<DataSampleMetaData> getAllSampleMetaData() throws DataAccessException {
		return h2Samples.getAllSampleMetaData();
	}

	/**
	 * Get a specific schema meta data object by its GUID
	 * 
	 * @param guid
	 *            the desired guid
	 * @return the SchemaMetaData bean that coincides with the GUID
	 * @throws DataAccessException 
	 */
	public SchemaMetaData getSchemaMetaDataByGuid(String guid) throws DataAccessException {
		SchemaMetaData schemaMetaData = new SchemaMetaData();
		schemaMetaData = h2Schema.getSchemaMetaDataByGuid(guid);
		return schemaMetaData;
	}

	/**
	 * Get a schema by its guid
	 * 
	 * @param guid
	 *            the schema's guid
	 * @param showHistogram
	 *            true if histogram data should be displayed, false if it should
	 *            be removed
	 * @return the Schema bean
	 * @throws DataAccessException 
	 */
	public Schema getSchemaByGuid(String guid, boolean showHistogram) throws DataAccessException {
		if(guid == null) {
			return null;
		}
		Schema schema = h2Schema.getSchemaByGuid(guid);

		if (!showHistogram) {
			for (String key : schema.getsProfile().keySet()) {
				Profile profile = schema.getsProfile().get(key);
				Detail detail = profile.getDetail();
				if (detail instanceof NumberDetail) {
					NumberDetail nm = ((NumberDetail) Profile.getNumberDetail(profile));
					nm.setFreqHistogram(null);
				} else if (detail instanceof StringDetail) {
					StringDetail sm = ((StringDetail) Profile.getStringDetail(profile));
					sm.setTermFreqHistogram(null);
				} else if (detail instanceof BinaryDetail) {
					logger.error("Detected as binary in " + getClass().getName() + ".");
				}
				profile.setDetail(detail);
			}
		}
		return schema;
	}

	/**
	 * Gets the field-descriptor
	 * 
	 * @param guid
	 *            The Schema's Guid
	 * @param showHistogram
	 *            True if histogram data should be displayed; False if it should
	 *            be removed
	 * @return
	 * @throws DataAccessException 
	 */
	public Map<String, Profile> getSchemaFieldByGuid(String guid, boolean showHistogram) throws DataAccessException {
		Map<String, Profile> map = new HashMap<String, Profile>();
		map = h2Schema.getSchemaFieldByGuid(guid);

		if (!showHistogram) {
			for (String key : map.keySet()) {
				Profile profile = map.get(key);
				Detail detail = profile.getDetail();
				if (detail instanceof NumberDetail) {
					NumberDetail nm = ((NumberDetail) Profile.getNumberDetail(profile));
					nm.setFreqHistogram(null);
				} else if (detail instanceof StringDetail) {
					StringDetail sm = ((StringDetail) Profile.getStringDetail(profile));
					sm.setTermFreqHistogram(null);
				} else if (detail instanceof BinaryDetail) {
					logger.error("Detected as binary in " + getClass().getName() + ".");
				}
				profile.setDetail(detail);
			}
		}
		return map;
	}

	/**
	 * Delete schema based on its guid
	 * 
	 * @param guid
	 * @throws DataAccessException 
	 */
	public void deleteSchemaFromDeletionQueue(String guid) throws DataAccessException {
		logger.info("Deleting schema " + guid +" from database.");
		h2Schema.deleteSchemaFromDeletionQueue(guid);
	}

	/**
	 * Add a sample
	 * 
	 * @param sample
	 *            the DataSample bean to be added
	 * @throws DataAccessException 
	 */
	public String addSample(DataSample sample) throws DataAccessException {
		return h2Samples.addSample(sample);
	}

	/**
	 * Call underlying H2SampleDAO class to retrieve a mapping of all the sample
	 * names to their respective media types in the database.
	 * 
	 * @return
	 * @throws DataAccessException 
	 */
	public Map<String, String> getExistingSampleNames() throws DataAccessException {
		return h2Samples.getExistingSampleNames();
	}

	/**
	 * Get a list of samples by their guids
	 * 
	 * @param guids
	 *            ordered list of guids
	 * @return an ordered list of DataSample beans
	 * @throws DataAccessException 
	 * @throws SQLException
	 */
	public List<DataSample> getSamplesByGuids(String[] guids) throws DataAccessException {
		List<DataSample> samples = new ArrayList<DataSample>();
		for (String guid : guids) {
			samples.add(h2Samples.getSampleByGuid(guid));
		}
		return samples;
	}

	/**
	 * Gets a given Data Sample bean given its Guid
	 * 
	 * @param guid
	 * @return
	 * @throws DataAccessException 
	 */
	public DataSample getSampleByGuid(String guid) throws DataAccessException {
		DataSample sample = new DataSample();

		sample = h2Samples.getSampleByGuid(guid);
		return sample;
	}

	/**
	 * Gets a Data Sample Meta Data bean given its Guid
	 * 
	 * @param guid
	 * @return
	 * @throws DataAccessException 
	 */
	public DataSampleMetaData getSampleMetaDataByGuid(String guid) throws DataAccessException {
		DataSampleMetaData sampleMetaData;

		sampleMetaData = h2Samples.getDataSampleMetaDataByGuid(guid);
		return sampleMetaData;
	}

	/**
	 * Gets the field-descriptor
	 * 
	 * @param guid
	 * @return
	 * @throws DataAccessException 
	 */
	public Map<String, Profile> getSampleFieldByGuid(String guid, boolean showHistogram) throws DataAccessException {
		Map<String, Profile> map = new HashMap<String, Profile>();
		map = h2Samples.getSampleFieldByGuid(guid);

		if (!showHistogram) {
			for (String key : map.keySet()) {
				Profile profile = map.get(key);
				Detail detail = profile.getDetail();
				if (detail instanceof NumberDetail) {
					NumberDetail nm = ((NumberDetail) Profile.getNumberDetail(profile));
					nm.setFreqHistogram(null);
				} else if (detail instanceof StringDetail) {
					StringDetail sm = ((StringDetail) Profile.getStringDetail(profile));
					sm.setTermFreqHistogram(null);
				} else if (detail instanceof BinaryDetail) {
					logger.error("Detected as binary in " + getClass().getName() + ".");
				}
				profile.setDetail(detail);
			}
		}
		return map;
	}

	public void deleteSchemaByGuid(String guid) throws DataAccessException {
		h2Schema.deleteSchemaByGuid(guid);
	}

	public void deleteSampleByGuid(String guid) throws DataAccessException {
		h2Samples.deleteSampleByGuid(guid);
	}

	/**
	 * Has logic to determine if a GUID is a Schema or Data Sample.
	 * 
	 * @param guid
	 *            An ambiguous GUID belonging to either a Schema or Data Sample
	 * @throws DataAccessException 
	 */
	public void deleteByGuid(String guid) throws DataAccessException {
		Schema schema = h2Schema.getSchemaByGuid(guid);
		DataSample sample = h2Samples.getSampleByGuid(guid);

		if (schema != null) {
			h2Schema.deleteSchemaByGuid(guid);
		} else if (sample != null) {
			h2Samples.deleteSampleByGuid(guid);
		} else {
			logger.error("No such guid exists in the database.");
			throw new DataAccessException("Error finding guid in H2 database");
		}
	}
	
	public static H2DataAccessObject getH2DAO() {
		return h2Dao;
	}

	public static void setH2DAO(H2DataAccessObject h2dao) {
		h2Dao = h2dao;
	}

	public H2MetricsDataAccessObject getH2Metrics() {
		return h2Metrics;
	}

	public H2SampleDataAccessObject getH2Samples() {
		return h2Samples;
	}

	public H2SchemaDataAccessObject getH2Schema() {
		return h2Schema;
	}

	public boolean testConnection() {
		return testConnection(h2Database.getDbConnection());
	}

	public boolean testConnection(Connection conn) {
		try{
			isLive = conn.isValid(5);
			return isLive;
		} catch(SQLException e) {
			return false;
		}
	}

	public boolean isLive() {
		return isLive;
	}

	/**
	 * Convenience method to turn a prepared statement into a string. Should not
	 * be used for anything other than debugging
	 * 
	 * @param ppst
	 * @return
	 * @throws SQLException
	 */
	private static String preparedStatementToString(PreparedStatement ppst) throws SQLException {

		String queryString = ppst.toString();
		queryString = queryString.substring(queryString.indexOf(':') + 1);
		if (!queryString.contains("{")) {
			return queryString;
		}
		String[] splits = queryString.split("\\{", 2);
		queryString = splits[0];
		String params = "{" + splits[1];
		String[] values = params.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
		for (int i = 0; i < values.length; i++) {
			String substitution = values[i].substring(values[i].indexOf(":") + 1);
			int markIndex = queryString.indexOf("?");
			queryString = queryString.substring(0, markIndex) + substitution.trim()
			+ queryString.substring(markIndex + 1);
		}
		queryString = queryString.substring(0, queryString.lastIndexOf("}"))
				+ queryString.substring(queryString.lastIndexOf("}") + 1);
		return queryString;
	}

	public H2Database getH2Database() {
		return h2Database;
	}

	public void setH2Database(H2Database h2Database) {
		this.h2Database = h2Database;
	}
}
